# Generated by Django 4.0.5 on 2022-06-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='f5_order',
            field=models.FileField(default='img.png', upload_to='f5'),
        ),
    ]
