# Generated by Django 4.0.5 on 2022-06-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
        migrations.AddField(
            model_name='key',
            name='f5_order',
            field=models.FileField(default='f5.txt', upload_to=''),
        ),
        migrations.AddField(
            model_name='key',
            name='private_key',
            field=models.FileField(default='public_key.pem', upload_to=''),
        ),
        migrations.AddField(
            model_name='key',
            name='public_key',
            field=models.FileField(default='public_key.pem', upload_to=''),
        ),
    ]
