# Generated by Django 4.0.5 on 2022-06-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_key_f5_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='f5_order',
            field=models.FileField(upload_to='f5'),
        ),
    ]
