# Generated by Django 4.0.5 on 2022-06-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_new_key_f5_order_key_private_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='key',
            name='public_key',
        ),
        migrations.AlterField(
            model_name='key',
            name='f5_order',
            field=models.FileField(upload_to=''),
        ),
    ]
