# Generated by Django 4.0.5 on 2022-06-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_key_f5_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='matrix_key',
            field=models.IntegerField(default=1),
        ),
    ]
