# Generated by Django 4.0.5 on 2022-06-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_key_private_key_remove_key_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='f5_order',
            field=models.FileField(upload_to='f5'),
        ),
    ]
