# Generated by Django 4.0.5 on 2022-06-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_key_matrix_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='matrix_key',
            field=models.IntegerField(),
        ),
    ]
