# Generated by Django 4.0.5 on 2022-06-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_key_f5_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='private_key',
            field=models.FileField(default='hi', upload_to='keys/private_keys'),
        ),
        migrations.AddField(
            model_name='key',
            name='public_key',
            field=models.FileField(default='hi', upload_to='keys/public_keys'),
        ),
    ]
