# Generated by Django 4.0.5 on 2022-06-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_key_matrix_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
