# Generated by Django 4.0.5 on 2022-06-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_key_private_key_key_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='private_key',
            field=models.FileField(upload_to='keys/private_keys'),
        ),
        migrations.AlterField(
            model_name='key',
            name='public_key',
            field=models.FileField(upload_to='keys/public_keys'),
        ),
    ]
