# Generated by Django 4.0.5 on 2022-06-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_key_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='image',
            field=models.ImageField(upload_to='encrypted_images'),
        ),
    ]
