# Generated by Django 4.0.5 on 2022-06-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_key_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='message',
            field=models.TextField(blank=True, default='hello', null=True),
        ),
    ]
