# Generated by Django 4.0.5 on 2022-06-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_key_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
