# Generated by Django 4.0.5 on 2022-06-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_message_remove_key_image_remove_key_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cipher_text',
            field=models.TextField(null=True),
        ),
    ]
